### ISSUE TITLE
tests fail on node 10 and 9

### ISSUE THREAD

**Issue by wildeyes** [felixhageloh/uebersicht#327]
node v10.9.0
```
~/D/u/server ❯❯❯ yarn && yarn test                                                                                                                                                                     ✘ 1
yarn install v1.9.4
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.54s.
yarn run v1.9.4
$ npm run-script test-local && npm run-script test-browser

> uebersicht-server@0.0.0 test-local ../uebersicht/server
> tape -r coffee-script/register spec/backend/**/* | tap-spec

    watching ../uebersicht/server/spec/test_widgets
    undefined

  starting on the specified port

    ✔ app should respond on port 3030

  dispatching events

    ✔ it dispatches WIDGET_ADDED events

  serving the client

    ✔ server responds to /some-screen-id
    ✔ it serves the client html
    ✔ server responds to /
    ✔ it serves the client html

  serving current state

    ✔ there should be 5 widgets
    ✔ there should be 5 widget settings entries
    ✔ screens should be an empty array

  recording screen ids

    ✔ it returns an updated array of screen ids

  running shell commands

    ✔ server responds to /run
    ✔ it serves command results

  serving static files in the widget dir

    ✔ it serves a static image

  closing

    ✔ it closes

  when a login shell option is provided

    watching ../uebersicht/server/spec/test_widgets
{ Error: read ECONNRESET
    at TCP.onread (net.js:1:1)
 errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
    200
    ✔ it indeed runs in a login shell

  bundling coffeescript widgets

    ✔ it returns a browserify bundle
{ Error: read ECONNRESET
    at TCP.onread (net.js:1:1)
 errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
    ✔ the source code it generates looks ok

  bundling javascript widgets

    ✔ it returns a browserify bundle
    ✔ the source code looks ok

  bundling widgets with syntax errors

    ✔ it returns a browserify bundle
    ✔ it spits out an error when bundling

  responding to POST /run/

    ✔ it ignores requests to other paths
    ✔ it ignores GET requests
    ✔ it reponds

  running commands

    ✔ it runs commands in the supplied working dir
    ✔ it runs commands

  shell type

    ✔ it is not a login shell

  running broken commands

    ✔ it responds with a 500 code
    ✔ it responds with an error message

  forwarding stderr

    ✔ it responds with a 500 code
    ✔ it sends stderr along

  closing

    ✔ it closes

  using a login shell

    ✔ it indeed runs in a login shell

  files that are already present in the widget dir

    watching ../uebersicht/server/spec/test_widgets
    ✔ it emits an event for all widgets already in the folder

  adding files

fs.js:127
  throw new ERR_INVALID_CALLBACK();
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:1:1)
    at Object.writeFile (fs.js:1:1)
    at Test.test (../uebersicht/server/spec/backend/directory_watcher_spec.js:1:1)
    at Test.bound [as _cb] (../uebersicht/server/node_modules/tape/lib/test.js:1:1)
    at Test.run (../uebersicht/server/node_modules/tape/lib/test.js:1:1)
    at Test.bound [as run] (../uebersicht/server/node_modules/tape/lib/test.js:1:1)
    at Immediate.next (../uebersicht/server/node_modules/tape/lib/results.js:1:1)
    at runCallback (timers.js:1:1)
    at tryOnImmediate (timers.js:1:1)
    at processImmediate (timers.js:1:1)



npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uebersicht-server@0.0.0 test-local: `tape -r coffee-script/register spec/backend/**/* | tap-spec`
npm ERR! Exit status 1
```

**Comment by hawkrives** [comment]
@wildeyes Have you tried with npm instead of Yarn? Yarn's going to update some packages, which may break things.

I'd try myself, but npm is currently not happy with me…

```
~/P/uebersicht/server (master|✔) $ npm install
npm ERR! Maximum call stack size exceeded

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rives/.npm/_logs/2018-10-22T14_48_22_201Z-debug.log
```

**Comment by wildeyes** [comment]
I got it too, so I tried deleting the [package-lock](https://github.com/npm/npm/issues/17056), which worked and produced a weird, different formatted package-lock, but yarn test still produced same error so tried with yarn and no package lock and same result.
dammit I wanted to work on this package! :(

**Comment by felixhageloh** [comment]
I think the issue is node 10 - the code is currently still on node 8

**Comment by felixhageloh** [comment]
sorry node 6 even. Next release should bring node 8

**Comment by wildeyes** [comment]
yep, just tried node 9, which got me:

```
error handling

    ✔ it catches and renders errors in render()
    ✔ it catches and renders errors in update()
    foo: oh noez!
    ✔ it renders command errors
    ✔ it recovers from command errors
    TypeError: Cannot set property 'innerHTML' of null
        at redraw (http://localhost:53436/bundle.js:37210:34)
        at http://localhost:53436/bundle.js:37133:9
        at http://localhost:53436/bundle.js:37582:7
        at Request.callback (http://localhost:53436/bundle.js:30325:3)
        at Request.<anonymous> (http://localhost:53436/bundle.js:30152:12)
        at Request.Emitter.emit (http://localhost:53436/bundle.js:3083:20)
        at XMLHttpRequest.xhr.onreadystatechange (http://localhost:53436/bundle.js:30419:10)
```

**Comment by wildeyes** [comment]
@felixhageloh which are the relevant issues for next-node release?

**Comment by felixhageloh** [comment]
on node 8 now. Will try node 10 in a bit (it just became the new LTS)
